import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import xarray as xr
import pandas as pd
import os

def generate_aiesda_report(dtg):
    pdf_filename = f"AIESDA_Report_{dtg}.pdf"
    pdf = matplotlib.backends.backend_pdf.PdfPages(pdf_filename)
    
    # --- PAGE 1: ANALYSIS INCREMENT (Where did the model change?) ---
    fig1 = plt.figure(figsize=(10, 8))
    ax1 = plt.axes(projection=ccrs.PlateCarree())
    ax1.set_extent([65, 98, 5, 38])
    ax1.coastlines(); ax1.add_feature(cfeature.BORDERS, linestyle=':')
    
    # Load data (generated by your earlier JEDI/Anemoi steps)
    inc = xr.open_dataset(f"inc_{dtg}.nc")['air_temperature']
    inc.plot(ax=ax1, transform=ccrs.PlateCarree(), cmap='RdBu_r', center=0)
    plt.title(f"AIESDA Analysis Increment: {dtg}\n(JEDI Analysis - Anemoi Background)")
    pdf.savefig(fig1)
    
    # --- PAGE 2: FORECAST SKILL (Did the DA help the future?) ---
    fig2 = plt.figure(figsize=(10, 6))
    # Load RMSE calculated from Step 18
    rmse_data = pd.read_csv(f"rmse_rollout_{dtg}.csv") 
    plt.plot(rmse_data['lead_time'], rmse_data['rmse_anemoi'], 'r--', label='Raw Anemoi')
    plt.plot(rmse_data['lead_time'], rmse_data['rmse_aiesda'], 'b-o', label='AIESDA (Assimilated)')
    plt.xlabel("Lead Time (Hours)"); plt.ylabel("RMSE (K)")
    plt.title(f"72-Hour Rollout Verification: {dtg}")
    plt.grid(True); plt.legend()
    pdf.savefig(fig2)
    
    # --- PAGE 3: STATION IMPACT (Observation Count) ---
    fig3 = plt.figure(figsize=(10, 8))
    # Plotting obs locations from your IODA file
    obs = xr.open_dataset(f"aiesda_obs_sfc_{dtg}.nc", group="MetaData")
    plt.scatter(obs['longitude'], obs['latitude'], c='green', s=10)
    plt.title(f"Observation Network Density for Cycle {dtg}")
    pdf.savefig(fig3)
    
    pdf.close()
    print(f"Operational Report Generated: {pdf_filename}")

# Run for current cycle
generate_aiesda_report(os.getenv('DTG', '2026011418'))
